# Generated by Django 3.2.5 on 2021-07-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_afisha', '0002_auto_20210705_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AddField(
            model_name='images',
            name='title',
            field=models.CharField(default='Картинка', max_length=200, verbose_name='Название'),
        ),
    ]
