# Generated by Django 3.2.5 on 2021-07-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_afisha', '0003_auto_20210705_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='place_id',
            field=models.CharField(default='new_place', max_length=100),
        ),
    ]
